### ISSUE TITLE
An error occurred while rendering. Rendering has stopped.

### ISSUE THREAD

**Issue by dcapeletti** [Gaia3D/mago3djs#615]
Hello,
I have a Revit model that weighs 71 MB, I have exported it to IFC which weighs 250 MB. Then with F4DConverter I rendered the file.
The output of the process is as follows.

```
F4DConverter.exe #inputFolder c:\demo_data #outputFolder c:\data\workshop #meshType 0 #log c:\data\workshop\result.txt #indexing y
[Info]Arguments are following.
#indexing : y
#inputFolder : c:\demo_data
#log : c:\data\workshop\result.txt
#meshType : 0
#outputFolder : c:\data\workshop
===== Start processing this file : MULTIPARASPARAGUAYPORK.ifc
Detected IFC version: IFC2X
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
WARNING! <5.26873064923412748328246,8.88811636329923970833988,1.82998894161823000281686>==<5.26873064923412748328246,8.88811636329923970833988,1.82998894161823000281686>
WARNING! <5.26873064923412748328246,8.88811636329923970833988,1.82998894161823000281686>==<5.26873064923412748328246,8.88811636329923970833988,1.82998894161823000281686>
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
carve::triangulate::incorporateHolesIntoPolygon failed
ItemShapeInputData::addClosedPolyhedron: Meshset is not closed
[Info]Vertex trimming done.
[Info]Exterior detection done.
[Info]Model/reference detection done. 4466 models out of 45863 meshes detected.
[Info]VBO of each mesh created.
[Info]Mesh distribution on each octree done.
[Info]Net Surface Mesh created.
```

When I enter the browser to view it, I can see the model on the ground, but after a few seconds when I try to zoom in to see details of it, the browser launches the following error.
```

An error occurred while rendering. Rendering has stopped.
RangeError: Invalid typed array length: 8822716227
RangeError: Invalid typed array length: 8822716227
    at new Int8Array (<anonymous>)
    at BlocksList.parseBlockVersioned (Shader.js:30765:35)
    at BlocksList.parseBlocksListVersioned (Shader.js:30874:22)
    at MagoManager.manageQueue (Shader.js:9362:18)
    at MagoManager.startRender (Shader.js:7263:8)
    at MagoManager.start (Shader.js:5768:8)
    at executeCommands (http://localhost/src/engine/cesium/Cesium.js:226607:35)
    at executeCommandsInViewport (http://localhost/src/engine/cesium/Cesium.js:226966:9)
    at updateAndExecuteCommands (http://localhost/src/engine/cesium/Cesium.js:226814:13)
    at render (http://localhost/src/engine/cesium/Cesium.js:227350:9)
```

I enclose images so that you can appreciate the error that occurs.
I hope you can help me how to solve this problem.

Thank you

**Model in load**
![model in load](https://user-images.githubusercontent.com/5890886/46885907-af062380-ce2f-11e8-9bf9-f8367a5884ac.png)
**Mistake when I approach the model**
![mistake when i approach the model](https://user-images.githubusercontent.com/5890886/46885911-b4fc0480-ce2f-11e8-859c-85d4330d8224.png)

**Comment by shire75** [comment]
Hi.

First, very sorry for late response.

Can i get your .ifc file to test?

To check correctly, we have to find out whether the error is caused by wrong conversion or by bugs in .js file.

Thanks.

**Comment by dcapeletti** [comment]
Hello, thank you for your answer.

Yes of course, I attach two files, the largest is the one that has problems, however the smallest file, does not have problems. Both files have been generated by Revit.  Attached image of the exporter of Revit.

I also exported the largest file to OBJ and got the same problem.

Greetings

![revit_2018-10-16_14-56-20](https://user-images.githubusercontent.com/5890886/47031908-5c867900-d147-11e8-8838-2652add9a53c.png)

**File one**
[PRUEBA.zip](https://github.com/Gaia3D/mago3djs/files/2484037/PRUEBA.zip)

**File two**
https://cloud.disroot.org/s/tDSQiGpaGEynXyA

**Comment by shire75** [comment]
Hello. 

Thanks for sharing your data.

It will take a time to go over this issue.

I will give you the result as soon as we clear this problem.

Thanks.

**Comment by dcapeletti** [comment]
Thank you very much for your reply. Your help will be very useful to me.

Greetings

**Comment by shire75** [comment]
Hi.

At last, we cleared this issue using the data you shared.

There were 2 critical bugs in the converter.(One of these 2 bugs caused the error.)

We will upload the latest version of .msi file on our site(www.mago3d.com) after updating and refreshing all source codes & documents on the github(www.github.com/Gaia3D/F4dConverter).

We will inform you again when the .msi file is uploaded.

Very thanks for giving the chance by which we could have good experience.

**Comment by dcapeletti** [comment]
Hi, the pleasure is mine when I can find bugs and solve problems on this wonderful platform. I'm glad you could find the error.

I will pay attention to the new version of MSI, evaluate it with other models and close this issue if everything went well.

Thank you

**Comment by shire75** [comment]
Hi.

The error-fixed converter is ready now on www.mago3d.com

Just download and test it. : )

Thanks.

**Comment by dcapeletti** [comment]
> 
> 
> Hi.
> 
> The error-fixed converter is ready now on [www.mago3d.com](http://www.mago3d.com)
> 
> Just download and test it. : )
> 
> Thanks.

Hello, I downloaded and installed version 0.0.3 of the converter and when I try to run it on console, I get an error. Attached is a screenshot of the error.
The command I launch in the converter is the following: 
`F4DConverter.exe #inputFolder c:\demo_data #outputFolder c:\data\workshop #meshType 0 #log c:\data\workshop\result.txt #indexing y`

Greetings
![explorer_2018-10-22_12-49-01](https://user-images.githubusercontent.com/5890886/47293484-a6a4aa00-d5e0-11e8-9d75-1b71ee37001d.png)

**Comment by dcapeletti** [comment]
> 
> 
> Hi.
> 
> The error-fixed converter is ready now on [www.mago3d.com](http://www.mago3d.com)
> 
> Just download and test it. : )
> 
> Thanks.

Prueba

**Comment by dcapeletti** [comment]
fds

**Comment by dcapeletti** [comment]
Hello, I downloaded and installed version 0.0.3 of the converter and when I try to run it on console, I get an error. Attached is a screenshot of the error.
The command I launch in the converter is the following:
F4DConverter.exe #inputFolder c:\demo_data #outputFolder c:\data\workshop #meshType 0 #log c:\data\workshop\result.txt #indexing y

Greetings

![explorer_2018-10-22_12-49-01](https://user-images.githubusercontent.com/5890886/47293871-c9838e00-d5e1-11e8-968d-44b09ccd8f5f.png)

**Comment by shire75** [comment]
Ooops. I forgot to add the .dll into the .msi package.

I uploaded the fixed .msi on the site.

Please, check it.

Sorry for your inconvenience.

Thanks.

**Comment by dcapeletti** [comment]
Hello, sorry for the delay.

I have done the conversion of several of our models, everything has gone well so far. This problem has been solved. We are happy with mago3d.

Thank you for your great work.
