### ISSUE TITLE
Error using changeObjectInfoViewModeAPI API

### ISSUE THREAD

**Issue by dcapeletti** [Gaia3D/mago3djs#616]
Hello, I have written the html code and javascript in my html file that appears on http://www.mago3d.com/homepage/api.do#changeObjectInfoViewModeAPI but when I allow the information to be displayed and click on an object, an error message appears.

```
Shader.js:36611 Uncaught TypeError: window[functionName] is not a function
    at clickPositionCallback (Shader.js:36611)
    at Shader.js:14633
    at handleMouseUp (Cesium.js:79515)
    at handlePointerUp (Cesium.js:79926)
    at HTMLCanvasElement.listener (Cesium.js:79369)
clickPositionCallback @ Shader.js:36611
(anonymous) @ Shader.js:14633
handleMouseUp @ Cesium.js:79515
handlePointerUp @ Cesium.js:79926
listener @ Cesium.js:79369
Cesium.js:237541 An error occurred while rendering.  Rendering has stopped.
undefined
TypeError: window[functionName] is not a function
TypeError: window[functionName] is not a function
    at selectedObjectCallback (Shader.js:36548:22)
    at MagoManager.selectedObjectNotice (Shader.js:13472:4)
    at MagoManager.startRender (Shader.js:7356:11)
    at MagoManager.start (Shader.js:5768:8)
    at executeCommands (http://localhost:8080/src/engine/cesium/Cesium.js:226607:35)
    at executeCommandsInViewport (http://localhost:8080/src/engine/cesium/Cesium.js:226966:9)
    at updateAndExecuteCommands (http://localhost:8080/src/engine/cesium/Cesium.js:226814:13)
    at render (http://localhost:8080/src/engine/cesium/Cesium.js:227350:9)
    at tryAndCatchError (http://localhost:8080/src/engine/cesium/Cesium.js:227368:13)
    at Scene.render (http://localhost:8080/src/engine/cesium/Cesium.js:227409:13)
CesiumWidget.showErrorPanel @ Cesium.js:237541
(anonymous) @ Cesium.js:237254
Event.raiseEvent @ Cesium.js:11283
tryAndCatchError @ Cesium.js:227370
Scene.render @ Cesium.js:227409
CesiumWidget.render @ Cesium.js:237591
render @ Cesium.js:236970
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:78954
render @ Cesium.js:236971
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:78954
render @ Cesium.js:236971
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:78954
render @ Cesium.js:236971
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:78954
render @ Cesium.js:236971
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:78954
render @ Cesium.js:236971
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:78954
render @ Cesium.js:236971
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:78954
render @ Cesium.js:236971
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:78954
render @ Cesium.js:236971
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:78954
render @ Cesium.js:236971
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:78954
render @ Cesium.js:236971
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:78954
render @ Cesium.js:236971
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:78954
render @ Cesium.js:236971
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:78954
render @ Cesium.js:236971
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:78954
render @ Cesium.js:236971
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:78954
render @ Cesium.js:236971
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:78954
render @ Cesium.js:236971
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:78954
render @ Cesium.js:236971
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:78954
render @ Cesium.js:236971
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:78954
render @ Cesium.js:236971
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:78954
render @ Cesium.js:236971
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:78954
render @ Cesium.js:236971
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:78954
render @ Cesium.js:236971
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:78954
render @ Cesium.js:236971
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:78954
render @ Cesium.js:236971
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:78954
render @ Cesium.js:236971
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:78954
render @ Cesium.js:236971
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:78954
render @ Cesium.js:236971
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:78954
render @ Cesium.js:236971
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:78954
render @ Cesium.js:236971
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:78954
render @ Cesium.js:236971
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:78954
render @ Cesium.js:236971
requestAnimationFrame (async)
requestAnimationFrame @ Cesium.js:78954
render @ Cesium.js:236971
```
Thanks

Attached screenshots.

![chrome_2018-10-18_18-18-43](https://user-images.githubusercontent.com/5890886/47175364-4e705e00-d2e9-11e8-8d4d-13e5c88019d8.png)

**Comment by dcapeletti** [comment]
I followed the trace of the javascript code in the browser and when it reaches the break point shown in the image, the error is launched. However, in the console I can see all the values of the variables that reach this function. Attached screenshot.

![chrome_2018-10-18_16-11-09](https://user-images.githubusercontent.com/5890886/47178075-80d18980-d2f0-11e8-9ba2-a9c7ba8a411b.png)

In this image I show when the error is captured with the information in the console.

![chrome_2018-10-18_16-17-52](https://user-images.githubusercontent.com/5890886/47178477-bcb91e80-d2f1-11e8-9124-999068048ab2.png)

Thanks

**Comment by cheonjeongdae** [comment]
**I used Google Translator.**

Callbacks are available in mago3D.
Define the function name to be called with callback in the policy-cesium.json file.
You can create a function in an html file.

See the example below.
The callback name and function name in the json file must be the same.

---- mago3djs source ----
policy-cesium.json
.....  skip ......
"geo_callback_enable": "true",
"geo_callback_apiresult": "showApiResult",
"geo_callback_dataInfo": "showDataInfo",
"geo_callback_selectedobject": "showSelectedObject",
"geo_callback_moveddata": "showMovedData",
"geo_callback_insertissue": "showInsertIssueLayer",
"geo_callback_clickposition": "showClickPosition",

showApiResult: result of api call
showDataInfo: data information display
.... skip .....
showClickPosition: Display click information

cesium.html
2101 line
function showClickPosition(position) {
.... skip ....
}

http://www.mago3d.com/homepage/demo.do
If you test the page by placing a breakpoint in Chrome Debugger mode
You can check.
github has data upload restriction, so test data can not be uploaded.

**Comment by dcapeletti** [comment]
Hello, thank you very much for your reply, it has been very helpful. Problem solved.

Greetings
